import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navLinks = [
  { href: '/', label: 'Quartet 소개' },
  { href: '/', label: '모든 카페' },
  { href: '/', label: '카페 지도' },
  { href: '/', label: '카페 일지' },
  { href: '/', label: '매장 등록' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="fixed top-0 flex w-full justify-between bg-white px-[70px] py-[16px] shadow-md">
          <nav className="flex items-center gap-x-[55px]">
            <Link href="/" className="cursor-pointer text-[24px] font-extrabold text-[#714016]">
              Quartet
            </Link>
            <ul className="flex items-center gap-x-[25px] text-[14px]">
              {navLinks.map((nav, index) => (
                <li key={index} className="hover:underline">
                  <Link href={nav.href}>{nav.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
          <button className="cursor-pointer">로그인</button>
          {/* 토큰 있을 때 이미지+OO님 */}
        </header>
        <main className="mt-16 p-4">{children}</main>
      </body>
    </html>
  );
}
